spring:
  application:
    name: courses
  security:
    oauth2:
      resourceserver:
        jwt:
          authority-prefix: ""
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: ${SERVER_PORT:8080}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}
  allowed-methods: GET, POST, PUT, DELETE
  allowed-headers: "*"
  allow-credentials: true

jwt:
  secret-key: ${JWT_SECRET_KEY}